export const sampleTests = [
  {
    id: "test-1",
    title: "JEE Main Mock Test #12",
    subject: "Physics, Chemistry, Mathematics",
    difficulty: "Medium",
    questions: 75,
    duration: 180,
    dueDate: "Feb 15, 2026",
    status: "assigned" as const,
    score: null,
    year: "12th" as const,
  },
  {
    id: "test-2",
    title: "Mechanics & Thermodynamics",
    subject: "Physics",
    difficulty: "Hard",
    questions: 30,
    duration: 60,
    dueDate: "Feb 12, 2026",
    status: "completed" as const,
    score: 87,
    year: "12th" as const,
  },
  {
    id: "test-3",
    title: "Organic Chemistry Marathon",
    subject: "Chemistry",
    difficulty: "Medium",
    questions: 40,
    duration: 90,
    dueDate: "Feb 10, 2026",
    status: "completed" as const,
    score: 72,
    year: "12th" as const,
  },
  {
    id: "test-4",
    title: "Calculus & Algebra",
    subject: "Mathematics",
    difficulty: "Easy",
    questions: 25,
    duration: 45,
    dueDate: "Feb 18, 2026",
    status: "assigned" as const,
    score: null,
    year: "12th" as const,
  },
  {
    id: "test-5",
    title: "JEE Advanced Pattern Test",
    subject: "Physics, Chemistry, Mathematics",
    difficulty: "Hard",
    questions: 54,
    duration: 180,
    dueDate: "Feb 20, 2026",
    status: "assigned" as const,
    score: null,
    year: "12th" as const,
  },
  {
    id: "test-6",
    title: "Basic Mechanics",
    subject: "Physics",
    difficulty: "Easy",
    questions: 25,
    duration: 45,
    dueDate: "Feb 14, 2026",
    status: "assigned" as const,
    score: null,
    year: "11th" as const,
  },
  {
    id: "test-7",
    title: "Chemical Bonding & Structure",
    subject: "Chemistry",
    difficulty: "Medium",
    questions: 30,
    duration: 60,
    dueDate: "Feb 11, 2026",
    status: "completed" as const,
    score: 78,
    year: "11th" as const,
  },
  {
    id: "test-8",
    title: "Trigonometry & Sets",
    subject: "Mathematics",
    difficulty: "Easy",
    questions: 20,
    duration: 40,
    dueDate: "Feb 16, 2026",
    status: "assigned" as const,
    score: null,
    year: "11th" as const,
  },
];

export const sampleQuestions = [
  {
    id: 1,
    subject: "Physics",
    text: "A particle moves in a circle of radius R with a constant speed v. The magnitude of average velocity after half revolution is:",
    options: ["2v/\u03c0", "v/\u03c0", "v/2", "2R/\u03c0t"],
    correct: 0,
    explanation:
      "After half revolution, displacement = 2R (diameter). Time for half revolution = \u03c0R/v. Average velocity = 2R/(\u03c0R/v) = 2v/\u03c0.",
  },
  {
    id: 2,
    subject: "Physics",
    text: "Two blocks of masses m and 2m are connected by a light string passing over a frictionless pulley. The tension in the string is:",
    options: ["2mg/3", "4mg/3", "mg/3", "mg"],
    correct: 1,
    explanation:
      "Using Newton's second law for Atwood machine: T = 2m\u00b7(2m)\u00b7g/(m+2m) = 4mg/3.",
  },
  {
    id: 3,
    subject: "Chemistry",
    text: "Which of the following compounds shows optical isomerism?",
    options: ["CH\u2083CHClBr", "CH\u2082Cl\u2082", "CHCl\u2083", "CCl\u2084"],
    correct: 0,
    explanation:
      "CH\u2083CHClBr has a chiral carbon (C bonded to 4 different groups: CH\u2083, H, Cl, Br), hence it shows optical isomerism.",
  },
  {
    id: 4,
    subject: "Chemistry",
    text: "The hybridization of carbon in CO\u2082 is:",
    options: ["sp", "sp\u00b2", "sp\u00b3", "dsp\u00b2"],
    correct: 0,
    explanation:
      "In CO\u2082, carbon forms 2 double bonds with oxygen atoms. Two regions of electron density result in sp hybridization.",
  },
  {
    id: 5,
    subject: "Mathematics",
    text: "If f(x) = x\u00b3 - 3x + 2, then f'(1) equals:",
    options: ["0", "1", "-2", "3"],
    correct: 0,
    explanation:
      "f'(x) = 3x\u00b2 - 3. At x = 1: f'(1) = 3(1) - 3 = 0.",
  },
];

export const sampleResults = {
  totalScore: 87,
  totalQuestions: 30,
  correctAnswers: 26,
  incorrectAnswers: 3,
  unattempted: 1,
  percentile: 94.2,
  subjectWise: [
    { subject: "Physics", score: 92, total: 10, color: "hsl(217, 91%, 60%)" },
    { subject: "Chemistry", score: 80, total: 10, color: "hsl(160, 84%, 39%)" },
    { subject: "Mathematics", score: 88, total: 10, color: "hsl(25, 95%, 53%)" },
  ],
  difficultyWise: [
    { name: "Easy", value: 10, color: "hsl(160, 84%, 39%)" },
    { name: "Medium", value: 12, color: "hsl(217, 91%, 60%)" },
    { name: "Hard", value: 8, color: "hsl(25, 95%, 53%)" },
  ],
};

export const sampleDetailedQuestions = [
  {
    questionId: "q1",
    questionText: "A particle moves in a circle of radius R with a constant speed v. The magnitude of average velocity after half revolution is:",
    selectedAnswer: "2v/\u03c0",
    correctAnswer: "2v/\u03c0",
    isCorrect: true,
    topic: "Circular Motion",
    subject: "Physics",
    explanation: "After half revolution, displacement = 2R (diameter). Time for half revolution = \u03c0R/v. Average velocity = 2R/(\u03c0R/v) = 2v/\u03c0.",
    improvisation: null,
  },
  {
    questionId: "q2",
    questionText: "Two blocks of masses m and 2m are connected by a light string passing over a frictionless pulley. The tension in the string is:",
    selectedAnswer: "2mg/3",
    correctAnswer: "4mg/3",
    isCorrect: false,
    topic: "Laws of Motion",
    subject: "Physics",
    explanation: "Using Newton's second law for Atwood machine: a = (2m-m)g/(2m+m) = g/3. Tension T = m(g+a) = m(g + g/3) = 4mg/3.",
    improvisation: "Review Atwood machine problems. Practice free body diagrams for pulley systems. Focus on writing equations for each mass separately before solving.",
  },
  {
    questionId: "q3",
    questionText: "Which of the following compounds shows optical isomerism?",
    selectedAnswer: "CH\u2083CHClBr",
    correctAnswer: "CH\u2083CHClBr",
    isCorrect: true,
    topic: "Stereochemistry",
    subject: "Chemistry",
    explanation: "CH\u2083CHClBr has a chiral carbon bonded to 4 different groups: CH\u2083, H, Cl, Br.",
    improvisation: null,
  },
  {
    questionId: "q4",
    questionText: "The hybridization of carbon in CO\u2082 is:",
    selectedAnswer: "sp\u00b2",
    correctAnswer: "sp",
    isCorrect: false,
    topic: "Chemical Bonding",
    subject: "Chemistry",
    explanation: "In CO\u2082, carbon forms 2 double bonds. Two regions of electron density = sp hybridization (linear geometry).",
    improvisation: "Remember: count regions of electron density, not bonds. Double/triple bonds count as one region. Practice with molecules like BeCl\u2082, C\u2082H\u2082.",
  },
  {
    questionId: "q5",
    questionText: "If f(x) = x\u00b3 - 3x + 2, then f'(1) equals:",
    selectedAnswer: "0",
    correctAnswer: "0",
    isCorrect: true,
    topic: "Differentiation",
    subject: "Mathematics",
    explanation: "f'(x) = 3x\u00b2 - 3. At x = 1: f'(1) = 3(1) - 3 = 0.",
    improvisation: null,
  },
  {
    questionId: "q6",
    questionText: "The value of the integral from 0 to \u03c0 of sin(x)dx is:",
    selectedAnswer: "1",
    correctAnswer: "2",
    isCorrect: false,
    topic: "Integration",
    subject: "Mathematics",
    explanation: "Integral of sin(x) = -cos(x). From 0 to \u03c0: -cos(\u03c0) - (-cos(0)) = 1 + 1 = 2.",
    improvisation: "Practice definite integrals of trigonometric functions. Remember to evaluate at both limits and subtract carefully. Review the antiderivatives of sin(x) and cos(x).",
  },
  {
    questionId: "q7",
    questionText: "A body is thrown vertically upward with velocity u. The maximum height reached is:",
    selectedAnswer: "u\u00b2/2g",
    correctAnswer: "u\u00b2/2g",
    isCorrect: true,
    topic: "Kinematics",
    subject: "Physics",
    explanation: "Using v\u00b2 = u\u00b2 - 2gh. At max height, v = 0. So h = u\u00b2/2g.",
    improvisation: null,
  },
  {
    questionId: "q8",
    questionText: "The pH of a 0.01M HCl solution is:",
    selectedAnswer: "2",
    correctAnswer: "2",
    isCorrect: true,
    topic: "Ionic Equilibrium",
    subject: "Chemistry",
    explanation: "HCl is a strong acid, fully dissociated. [H+] = 0.01M = 10^-2. pH = -log(10^-2) = 2.",
    improvisation: null,
  },
  {
    questionId: "q9",
    questionText: "The determinant of a 2x2 matrix [[a,b],[c,d]] is:",
    selectedAnswer: null,
    correctAnswer: "ad - bc",
    isCorrect: false,
    topic: "Matrices",
    subject: "Mathematics",
    explanation: "The determinant of a 2x2 matrix is calculated as ad - bc (product of main diagonal minus product of other diagonal).",
    improvisation: "This question was skipped. Review 2x2 determinant formula and practice with numerical examples before moving to 3x3 determinants.",
  },
  {
    questionId: "q10",
    questionText: "Work done by a conservative force in a closed loop is:",
    selectedAnswer: "Zero",
    correctAnswer: "Zero",
    isCorrect: true,
    topic: "Work & Energy",
    subject: "Physics",
    explanation: "Conservative forces like gravity and spring force do zero net work in a closed loop because work depends only on initial and final positions.",
    improvisation: null,
  },
];

export const sampleSubjectWiseMarks = {
  "11th": [
    { subject: "Physics 1", scores: [65, 72, 68, 75, 78], avg: 71.6 },
    { subject: "Chemistry 1", scores: [70, 68, 74, 72, 78], avg: 72.4 },
    { subject: "Mathematics 1", scores: [80, 75, 82, 78, 85], avg: 80.0 },
  ],
  "12th": [
    { subject: "Physics 2", scores: [78, 82, 85, 88, 92], avg: 85.0 },
    { subject: "Chemistry 2", scores: [72, 75, 78, 80, 80], avg: 77.0 },
    { subject: "Mathematics 2", scores: [85, 82, 88, 90, 91], avg: 87.2 },
  ],
};

export const sampleProgress = {
  overallRank: 1247,
  totalStudents: 15000,
  streak: 12,
  testsCompleted: 28,
  avgScore: 82,
  rankHistory: [
    { week: "W1", rank: 3200 },
    { week: "W2", rank: 2800 },
    { week: "W3", rank: 2400 },
    { week: "W4", rank: 1900 },
    { week: "W5", rank: 1600 },
    { week: "W6", rank: 1247 },
  ],
  topicMastery: [
    { topic: "Mechanics", mastery: 88 },
    { topic: "Thermodynamics", mastery: 75 },
    { topic: "Electrostatics", mastery: 92 },
    { topic: "Optics", mastery: 68 },
    { topic: "Organic Chemistry", mastery: 72 },
    { topic: "Inorganic Chemistry", mastery: 85 },
    { topic: "Physical Chemistry", mastery: 79 },
    { topic: "Calculus", mastery: 91 },
    { topic: "Algebra", mastery: 83 },
    { topic: "Coordinate Geometry", mastery: 77 },
  ],
};

export const sampleLibrary = [
  {
    id: "lib-1",
    title: "NCERT Physics Class 12",
    subject: "Physics",
    type: "PDF",
    chapters: 15,
    downloaded: true,
    year: "12th" as const,
  },
  {
    id: "lib-2",
    title: "HC Verma - Concepts of Physics",
    subject: "Physics",
    type: "PDF",
    chapters: 47,
    downloaded: false,
    year: "12th" as const,
  },
  {
    id: "lib-3",
    title: "Morrison & Boyd - Organic Chemistry",
    subject: "Chemistry",
    type: "PDF",
    chapters: 36,
    downloaded: true,
    year: "12th" as const,
  },
  {
    id: "lib-4",
    title: "RD Sharma - Mathematics",
    subject: "Mathematics",
    type: "PDF",
    chapters: 33,
    downloaded: false,
    year: "12th" as const,
  },
  {
    id: "lib-5",
    title: "Previous Year Questions (2015-2025)",
    subject: "All",
    type: "Question Bank",
    chapters: 10,
    downloaded: true,
    year: "12th" as const,
  },
  {
    id: "lib-6",
    title: "NCERT Physics Class 11",
    subject: "Physics",
    type: "PDF",
    chapters: 15,
    downloaded: true,
    year: "11th" as const,
  },
  {
    id: "lib-7",
    title: "NCERT Chemistry Class 11",
    subject: "Chemistry",
    type: "PDF",
    chapters: 14,
    downloaded: false,
    year: "11th" as const,
  },
  {
    id: "lib-8",
    title: "RS Aggarwal - Mathematics Class 11",
    subject: "Mathematics",
    type: "PDF",
    chapters: 30,
    downloaded: true,
    year: "11th" as const,
  },
];

export const sampleTeacherData = {
  recentPapers: [
    {
      id: "paper-1",
      title: "JEE Main Mock #12",
      created: "Feb 8, 2026",
      questions: 75,
      assigned: true,
      students: 45,
    },
    {
      id: "paper-2",
      title: "Physics Unit Test - Rotation",
      created: "Feb 5, 2026",
      questions: 30,
      assigned: true,
      students: 38,
    },
    {
      id: "paper-3",
      title: "Chemistry Practice Set",
      created: "Feb 2, 2026",
      questions: 40,
      assigned: false,
      students: 0,
    },
  ],
  classes: [
    {
      id: "class-1",
      name: "JEE 2026 Batch A",
      students: 45,
      avgScore: 78,
    },
    {
      id: "class-2",
      name: "JEE 2026 Batch B",
      students: 38,
      avgScore: 72,
    },
    {
      id: "class-3",
      name: "JEE 2027 Foundation",
      students: 52,
      avgScore: 65,
    },
  ],
  performanceOverview: [
    { subject: "Physics", avg: 76 },
    { subject: "Chemistry", avg: 72 },
    { subject: "Mathematics", avg: 80 },
  ],
};

export const sampleLessonPlans = [
  {
    id: "lp-1",
    subject: "Physics",
    year: "11th" as const,
    topic: "Newton's Laws of Motion",
    objectives: ["Understand the three laws of motion", "Apply Newton's laws to solve problems", "Analyze free body diagrams"],
    activities: ["Interactive demo with spring balance", "Problem-solving session", "Group discussion on real-world applications"],
    duration: 90,
    status: "published" as const,
  },
  {
    id: "lp-2",
    subject: "Physics",
    year: "12th" as const,
    topic: "Electromagnetic Induction",
    objectives: ["Understand Faraday's law", "Calculate induced EMF", "Apply Lenz's law"],
    activities: ["Lab demonstration with coils", "Numerical problem practice", "Conceptual quiz"],
    duration: 75,
    status: "published" as const,
  },
  {
    id: "lp-3",
    subject: "Chemistry",
    year: "11th" as const,
    topic: "Chemical Bonding & Molecular Structure",
    objectives: ["Understand types of bonds", "Predict molecular geometry", "Apply VSEPR theory"],
    activities: ["Molecular model building", "Worksheet on hybridization", "Quiz on bond properties"],
    duration: 60,
    status: "draft" as const,
  },
  {
    id: "lp-4",
    subject: "Chemistry",
    year: "12th" as const,
    topic: "Coordination Compounds",
    objectives: ["Nomenclature of complexes", "Crystal field theory", "Isomerism in complexes"],
    activities: ["Naming exercises", "Color prediction activity", "Problem set"],
    duration: 90,
    status: "published" as const,
  },
  {
    id: "lp-5",
    subject: "Mathematics",
    year: "11th" as const,
    topic: "Trigonometric Functions",
    objectives: ["Master trig identities", "Solve trigonometric equations", "Graph trig functions"],
    activities: ["Identity proof practice", "Graphing exercise", "Application problems"],
    duration: 60,
    status: "draft" as const,
  },
  {
    id: "lp-6",
    subject: "Mathematics",
    year: "12th" as const,
    topic: "Definite Integrals & Applications",
    objectives: ["Properties of definite integrals", "Area under curves", "Application in physics"],
    activities: ["Step-by-step integration practice", "Area calculation problems", "Cross-subject examples"],
    duration: 75,
    status: "published" as const,
  },
];

export const sampleAdminStats = {
  totalStudents: 485,
  totalTeachers: 24,
  activeTests: 12,
  passRate: 78.5,
  departments: [
    { subject: "Physics", teachers: 8, students: 485, avgScore: 76 },
    { subject: "Chemistry", teachers: 8, students: 485, avgScore: 72 },
    { subject: "Mathematics", teachers: 8, students: 485, avgScore: 80 },
  ],
  recentActivity: [
    { id: "a1", text: "Dr. Sharma created JEE Main Mock #12", time: "2 hours ago", type: "paper" as const },
    { id: "a2", text: "15 students completed Physics Unit Test", time: "4 hours ago", type: "test" as const },
    { id: "a3", text: "New study material uploaded for Chemistry", time: "1 day ago", type: "material" as const },
    { id: "a4", text: "Batch B average score improved by 5%", time: "2 days ago", type: "achievement" as const },
    { id: "a5", text: "Dr. Patel published a new lesson plan", time: "3 days ago", type: "plan" as const },
  ],
};

export const sampleUsers = [
  { id: "u1", name: "Rahul Kumar", role: "student" as const, subject: null, year: "12th" as const, status: "active" as const, email: "rahul@example.com" },
  { id: "u2", name: "Priya Singh", role: "student" as const, subject: null, year: "12th" as const, status: "active" as const, email: "priya@example.com" },
  { id: "u3", name: "Amit Verma", role: "student" as const, subject: null, year: "11th" as const, status: "active" as const, email: "amit@example.com" },
  { id: "u4", name: "Sneha Patel", role: "student" as const, subject: null, year: "11th" as const, status: "inactive" as const, email: "sneha@example.com" },
  { id: "u5", name: "Dr. Sharma", role: "teacher" as const, subject: "Physics", year: null, status: "active" as const, email: "sharma@example.com" },
  { id: "u6", name: "Dr. Gupta", role: "teacher" as const, subject: "Chemistry", year: null, status: "active" as const, email: "gupta@example.com" },
  { id: "u7", name: "Prof. Verma", role: "teacher" as const, subject: "Mathematics", year: null, status: "active" as const, email: "verma@example.com" },
  { id: "u8", name: "Dr. Patel", role: "teacher" as const, subject: "Physics", year: null, status: "inactive" as const, email: "patel@example.com" },
  { id: "u9", name: "Ravi Shankar", role: "student" as const, subject: null, year: "12th" as const, status: "active" as const, email: "ravi@example.com" },
  { id: "u10", name: "Ananya Das", role: "student" as const, subject: null, year: "11th" as const, status: "active" as const, email: "ananya@example.com" },
];

export const sampleContentItems = [
  { id: "c1", title: "Rotation Dynamics - Notes", uploadedBy: "Dr. Sharma", subject: "Physics", date: "Feb 10, 2026", status: "pending" as const },
  { id: "c2", title: "Organic Reactions Flowchart", uploadedBy: "Dr. Gupta", subject: "Chemistry", date: "Feb 9, 2026", status: "pending" as const },
  { id: "c3", title: "Integration Shortcuts PDF", uploadedBy: "Prof. Verma", subject: "Mathematics", date: "Feb 8, 2026", status: "approved" as const },
  { id: "c4", title: "Thermodynamics Formula Sheet", uploadedBy: "Dr. Sharma", subject: "Physics", date: "Feb 7, 2026", status: "approved" as const },
  { id: "c5", title: "Electrochemistry Practice Set", uploadedBy: "Dr. Gupta", subject: "Chemistry", date: "Feb 6, 2026", status: "rejected" as const },
  { id: "c6", title: "Probability & Statistics Notes", uploadedBy: "Prof. Verma", subject: "Mathematics", date: "Feb 5, 2026", status: "pending" as const },
];

export const sampleBillingReports = {
  plan: "Institution Pro",
  studentsAllowed: 500,
  studentsUsed: 485,
  monthlyUsage: [
    { month: "Sep", tests: 45, papers: 12 },
    { month: "Oct", tests: 52, papers: 15 },
    { month: "Nov", tests: 68, papers: 18 },
    { month: "Dec", tests: 40, papers: 10 },
    { month: "Jan", tests: 75, papers: 22 },
    { month: "Feb", tests: 38, papers: 14 },
  ],
  renewalDate: "Mar 15, 2026",
};

export const sampleNotifications = [
  {
    id: "notif-1",
    title: "New Test Assigned",
    message: "JEE Main Mock Test #12 has been assigned. Due: Feb 15",
    time: "2 hours ago",
    read: false,
    type: "test" as const,
  },
  {
    id: "notif-2",
    title: "Results Ready",
    message: "Your Mechanics & Thermodynamics test results are ready!",
    time: "1 day ago",
    read: false,
    type: "result" as const,
  },
  {
    id: "notif-3",
    title: "Daily Streak",
    message: "You're on a 12-day streak! Keep it up!",
    time: "1 day ago",
    read: true,
    type: "streak" as const,
  },
  {
    id: "notif-4",
    title: "New Material Added",
    message: "Your teacher uploaded Rotation chapter notes",
    time: "3 days ago",
    read: true,
    type: "material" as const,
  },
];
